version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
  user:
    container_name: user
    build:
      context: .
      dockerfile: Dockerfile.user
    depends_on:
      - db1
    networks:
      - test
    ports:
      - 8080:8080
  db1:
    container_name: db1
    build:
      context: .
      dockerfile: Dockerfile.db1
    ports:
      - 27017:27017
    depends_on:
      - db2
      - db3
      - db4
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: test
    #   MONGO_INITDB_ROOT_PASSWORD: test
    volumes:
      - mongodb_data:/data/db
    networks:
      - test
  db2:
    image: mongo:latest
    container_name: db2
    ports:
      - 27018:27017
    command: ["mongod", "--replSet", "rs0","--bind_ip_all"]
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: test
    #   MONGO_INITDB_ROOT_PASSWORD: test
    volumes:
      - mongodb_data2:/data/db
    networks:
      - test
  db3:
    image: mongo:latest
    container_name: db3
    ports:
      - 27019:27017
    command: ["mongod", "--replSet", "rs0"]
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: test
    #   MONGO_INITDB_ROOT_PASSWORD: test
    volumes:
      - mongodb_data3:/data/db
    networks:
      - test
  db4:
    image: mongo:latest
    container_name: db4
    ports:
      - 27020:27017
    command: ["mongod", "--replSet", "rs0"]
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: test
    #   MONGO_INITDB_ROOT_PASSWORD: test
    volumes:
      - mongodb_data4:/data/db
    networks:
      - test
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: db1,db2,db3,db4
      # ME_CONFIG_MONGODB_ADMINUSERNAME: test
      # ME_CONFIG_MONGODB_ADMINPASSWORD: test
      # ME_CONFIG_BASICAUTH_USERNAME: admin
      # ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - db1
    networks:
      - test
volumes:
  mongodb_data:
  mongodb_data2:
  mongodb_data3:
  mongodb_data4:
networks:
  test:
